image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - staging

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


build_job:
  stage: build
  script:
  #- yarn -v
  #- yarn install
  # gitlab has problem with DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )" and produces error "bad substitution"
  #- uname -a # coreos
  #- readlink /bin/sh # dash
  - chmod +x ./websites/main/build.sh
  - ./websites/main/build.sh
  - chmod +x ./websites/landing/build.sh
  - ./websites/landing/build.sh



stage_deploy:
  only:
  - dmaster
  stage: staging
  script:
  - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  - ssh -p2017 rs@145.239.85.163 "sh /var/www/update.sh"

